network:
    ethernets:
        ens160:
            addresses: [10.0.0.11/24]
            gateway4: 10.0.0.1
            dhcp4: false
            nameservers:
                addresses:
                  - 8.8.8.8
                  - 8.8.4.4
                search: []
    version: 2
